import { ProductInventory, LocationInventorySummary } from '../types/inventory';
import { ReorderRecommendation } from '../types/reorder';
import { InventoryEvent } from '../types/events';

export const MOCK_LOCATIONS: LocationInventorySummary[] = [
  {
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    city: 'Mumbai',
    totalSkus: 24,
    totalUnits: 14250,
    inventoryValue: 348900,
    healthyPercent: 70.8,
    criticalCount: 3,
    reorderSoonCount: 4,
  },
  {
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    city: 'Delhi NCR',
    totalSkus: 20,
    totalUnits: 11800,
    inventoryValue: 284500,
    healthyPercent: 65.0,
    criticalCount: 4,
    reorderSoonCount: 3,
  },
  {
    locationId: 'LOC-BLR-01',
    locationName: 'Bengaluru Tech Park Warehouse',
    city: 'Bengaluru',
    totalSkus: 18,
    totalUnits: 9600,
    inventoryValue: 241200,
    healthyPercent: 83.3,
    criticalCount: 1,
    reorderSoonCount: 2,
  },
  {
    locationId: 'LOC-HYD-01',
    locationName: 'Hyderabad Regional Depot',
    city: 'Hyderabad',
    totalSkus: 16,
    totalUnits: 8400,
    inventoryValue: 198600,
    healthyPercent: 75.0,
    criticalCount: 2,
    reorderSoonCount: 2,
  },
];

export const INITIAL_MOCK_PRODUCTS: ProductInventory[] = [
  {
    id: 'inv-001',
    productId: 'prod-001',
    sku: 'SKU-ERG-902',
    name: 'Pro-Ergo Wireless Mechanical Keyboard',
    category: 'Electronics',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    currentStock: 14,
    reservedStock: 4,
    availableStock: 10,
    safetyStock: 30,
    reorderPoint: 85,
    unitCost: 65.0,
    dailyDemand: 11,
    daysOfStock: 0.9,
    status: 'CRITICAL',
    supplier: {
      id: 'sup-keychron',
      name: 'Keyronix Components Ltd',
      leadTimeDays: 5,
      reliabilityRate: 0.94,
      contactEmail: 'orders@keyronix.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 88, dailyDemand: 12, reorderPoint: 85 },
      { date: 'Sep 13', stockLevel: 75, dailyDemand: 13, reorderPoint: 85 },
      { date: 'Sep 14', stockLevel: 62, dailyDemand: 13, reorderPoint: 85 },
      { date: 'Sep 15', stockLevel: 48, dailyDemand: 14, reorderPoint: 85 },
      { date: 'Sep 16', stockLevel: 36, dailyDemand: 12, reorderPoint: 85 },
      { date: 'Sep 17', stockLevel: 22, dailyDemand: 14, reorderPoint: 85 },
      { date: 'Sep 18', stockLevel: 10, dailyDemand: 12, reorderPoint: 85 },
    ],
    lastUpdated: '2026-09-19T09:40:00Z',
  },
  {
    id: 'inv-002',
    productId: 'prod-002',
    sku: 'SKU-ANC-404',
    name: 'Noise-Cancelling Studio Headphones Gen-3',
    category: 'Electronics',
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    currentStock: 18,
    reservedStock: 6,
    availableStock: 12,
    safetyStock: 25,
    reorderPoint: 67,
    unitCost: 110.0,
    dailyDemand: 7,
    daysOfStock: 1.7,
    status: 'CRITICAL',
    supplier: {
      id: 'sup-audiotech',
      name: 'SonicWave Acoustics',
      leadTimeDays: 6,
      reliabilityRate: 0.91,
      contactEmail: 'b2b@sonicwave.io',
    },
    history: [
      { date: 'Sep 12', stockLevel: 70, dailyDemand: 8, reorderPoint: 67 },
      { date: 'Sep 13', stockLevel: 61, dailyDemand: 9, reorderPoint: 67 },
      { date: 'Sep 14', stockLevel: 51, dailyDemand: 10, reorderPoint: 67 },
      { date: 'Sep 15', stockLevel: 41, dailyDemand: 10, reorderPoint: 67 },
      { date: 'Sep 16', stockLevel: 30, dailyDemand: 11, reorderPoint: 67 },
      { date: 'Sep 17', stockLevel: 21, dailyDemand: 9, reorderPoint: 67 },
      { date: 'Sep 18', stockLevel: 12, dailyDemand: 9, reorderPoint: 67 },
    ],
    lastUpdated: '2026-09-19T08:15:00Z',
  },
  {
    id: 'inv-003',
    productId: 'prod-003',
    sku: 'SKU-THERM-101',
    name: 'Vacuum Insulated Stainless Tumbler 750ml',
    category: 'Home & Kitchen',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    currentStock: 52,
    reservedStock: 12,
    availableStock: 40,
    safetyStock: 20,
    reorderPoint: 56,
    unitCost: 14.5,
    dailyDemand: 9,
    daysOfStock: 4.4,
    status: 'REORDER_SOON',
    supplier: {
      id: 'sup-hydrosteel',
      name: 'HydroSteel Manufacturing',
      leadTimeDays: 4,
      reliabilityRate: 0.98,
      contactEmail: 'supply@hydrosteel.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 105, dailyDemand: 10, reorderPoint: 56 },
      { date: 'Sep 13', stockLevel: 94, dailyDemand: 11, reorderPoint: 56 },
      { date: 'Sep 14', stockLevel: 82, dailyDemand: 12, reorderPoint: 56 },
      { date: 'Sep 15', stockLevel: 70, dailyDemand: 12, reorderPoint: 56 },
      { date: 'Sep 16', stockLevel: 59, dailyDemand: 11, reorderPoint: 56 },
      { date: 'Sep 17', stockLevel: 49, dailyDemand: 10, reorderPoint: 56 },
      { date: 'Sep 18', stockLevel: 40, dailyDemand: 9, reorderPoint: 56 },
    ],
    lastUpdated: '2026-09-19T10:02:00Z',
  },
  {
    id: 'inv-004',
    productId: 'prod-004',
    sku: 'SKU-USB-C-240',
    name: 'Braided 240W Thunderbolt 4 Fast Cable (2m)',
    category: 'Electronics',
    locationId: 'LOC-BLR-01',
    locationName: 'Bengaluru Tech Park Warehouse',
    currentStock: 95,
    reservedStock: 15,
    availableStock: 80,
    safetyStock: 40,
    reorderPoint: 110,
    unitCost: 8.2,
    dailyDemand: 14,
    daysOfStock: 5.7,
    status: 'REORDER_SOON',
    supplier: {
      id: 'sup-cabletech',
      name: 'NexLink Connectors',
      leadTimeDays: 5,
      reliabilityRate: 0.97,
      contactEmail: 'sales@nexlink.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 165, dailyDemand: 15, reorderPoint: 110 },
      { date: 'Sep 13', stockLevel: 150, dailyDemand: 15, reorderPoint: 110 },
      { date: 'Sep 14', stockLevel: 134, dailyDemand: 16, reorderPoint: 110 },
      { date: 'Sep 15', stockLevel: 118, dailyDemand: 16, reorderPoint: 110 },
      { date: 'Sep 16', stockLevel: 104, dailyDemand: 14, reorderPoint: 110 },
      { date: 'Sep 17', stockLevel: 91, dailyDemand: 13, reorderPoint: 110 },
      { date: 'Sep 18', stockLevel: 80, dailyDemand: 14, reorderPoint: 110 },
    ],
    lastUpdated: '2026-09-19T09:12:00Z',
  },
  {
    id: 'inv-005',
    productId: 'prod-005',
    sku: 'SKU-LUM-DESK',
    name: 'Ultra-Slim LED Monitor Light Bar with Auto-Dimming',
    category: 'Electronics',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    currentStock: 240,
    reservedStock: 20,
    availableStock: 220,
    safetyStock: 30,
    reorderPoint: 60,
    unitCost: 32.0,
    dailyDemand: 5,
    daysOfStock: 44.0,
    status: 'HEALTHY',
    supplier: {
      id: 'sup-lumina',
      name: 'Lumina Opto-Electronics',
      leadTimeDays: 6,
      reliabilityRate: 0.95,
      contactEmail: 'ops@luminaopto.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 250, dailyDemand: 5, reorderPoint: 60 },
      { date: 'Sep 13', stockLevel: 245, dailyDemand: 5, reorderPoint: 60 },
      { date: 'Sep 14', stockLevel: 239, dailyDemand: 6, reorderPoint: 60 },
      { date: 'Sep 15', stockLevel: 234, dailyDemand: 5, reorderPoint: 60 },
      { date: 'Sep 16', stockLevel: 230, dailyDemand: 4, reorderPoint: 60 },
      { date: 'Sep 17', stockLevel: 225, dailyDemand: 5, reorderPoint: 60 },
      { date: 'Sep 18', stockLevel: 220, dailyDemand: 5, reorderPoint: 60 },
    ],
    lastUpdated: '2026-09-19T07:30:00Z',
  },
  {
    id: 'inv-006',
    productId: 'prod-006',
    sku: 'SKU-DESK-MAT-XL',
    name: 'Water-Resistant Felt & Vegan Leather Desk Pad XL',
    category: 'Home & Office',
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    currentStock: 780,
    reservedStock: 30,
    availableStock: 750,
    safetyStock: 50,
    reorderPoint: 110,
    unitCost: 12.0,
    dailyDemand: 8,
    daysOfStock: 93.8,
    status: 'OVERSTOCKED',
    supplier: {
      id: 'sup-matpro',
      name: 'Artisan Workspace Goods',
      leadTimeDays: 5,
      reliabilityRate: 0.99,
      contactEmail: 'contact@artisanworkspace.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 800, dailyDemand: 8, reorderPoint: 110 },
      { date: 'Sep 13', stockLevel: 792, dailyDemand: 8, reorderPoint: 110 },
      { date: 'Sep 14', stockLevel: 783, dailyDemand: 9, reorderPoint: 110 },
      { date: 'Sep 15', stockLevel: 775, dailyDemand: 8, reorderPoint: 110 },
      { date: 'Sep 16', stockLevel: 766, dailyDemand: 9, reorderPoint: 110 },
      { date: 'Sep 17', stockLevel: 758, dailyDemand: 8, reorderPoint: 110 },
      { date: 'Sep 18', stockLevel: 750, dailyDemand: 8, reorderPoint: 110 },
    ],
    lastUpdated: '2026-09-19T06:45:00Z',
  },
  {
    id: 'inv-007',
    productId: 'prod-007',
    sku: 'SKU-SERUM-VITC',
    name: 'Antioxidant Vitamin C Glow Serum 30ml',
    category: 'Health & Beauty',
    locationId: 'LOC-HYD-01',
    locationName: 'Hyderabad Regional Depot',
    currentStock: 16,
    reservedStock: 8,
    availableStock: 8,
    safetyStock: 25,
    reorderPoint: 73,
    unitCost: 18.0,
    dailyDemand: 8,
    daysOfStock: 1.0,
    status: 'CRITICAL',
    supplier: {
      id: 'sup-derma',
      name: 'BioDerma Labs',
      leadTimeDays: 6,
      reliabilityRate: 0.92,
      contactEmail: 'supply@biodermalabs.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 65, dailyDemand: 9, reorderPoint: 73 },
      { date: 'Sep 13', stockLevel: 55, dailyDemand: 10, reorderPoint: 73 },
      { date: 'Sep 14', stockLevel: 44, dailyDemand: 11, reorderPoint: 73 },
      { date: 'Sep 15', stockLevel: 34, dailyDemand: 10, reorderPoint: 73 },
      { date: 'Sep 16', stockLevel: 24, dailyDemand: 10, reorderPoint: 73 },
      { date: 'Sep 17', stockLevel: 15, dailyDemand: 9, reorderPoint: 73 },
      { date: 'Sep 18', stockLevel: 8, dailyDemand: 8, reorderPoint: 73 },
    ],
    lastUpdated: '2026-09-19T09:50:00Z',
  },
  {
    id: 'inv-008',
    productId: 'prod-008',
    sku: 'SKU-COFFEE-ETH',
    name: 'Single-Origin Ethiopian Yirgacheffe Beans 1kg',
    category: 'Food & Beverage',
    locationId: 'LOC-BLR-01',
    locationName: 'Bengaluru Tech Park Warehouse',
    currentStock: 140,
    reservedStock: 15,
    availableStock: 125,
    safetyStock: 35,
    reorderPoint: 75,
    unitCost: 22.0,
    dailyDemand: 6,
    daysOfStock: 20.8,
    status: 'HEALTHY',
    supplier: {
      id: 'sup-roasters',
      name: 'Highland Artisan Roasters',
      leadTimeDays: 4,
      reliabilityRate: 0.96,
      contactEmail: 'orders@highlandroasters.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 160, dailyDemand: 6, reorderPoint: 75 },
      { date: 'Sep 13', stockLevel: 154, dailyDemand: 6, reorderPoint: 75 },
      { date: 'Sep 14', stockLevel: 148, dailyDemand: 6, reorderPoint: 75 },
      { date: 'Sep 15', stockLevel: 142, dailyDemand: 6, reorderPoint: 75 },
      { date: 'Sep 16', stockLevel: 136, dailyDemand: 6, reorderPoint: 75 },
      { date: 'Sep 17', stockLevel: 130, dailyDemand: 5, reorderPoint: 75 },
      { date: 'Sep 18', stockLevel: 125, dailyDemand: 6, reorderPoint: 75 },
    ],
    lastUpdated: '2026-09-19T08:55:00Z',
  },
  {
    id: 'inv-009',
    productId: 'prod-009',
    sku: 'SKU-AIR-PURIFY',
    name: 'True HEPA Smart Room Air Purifier H13',
    category: 'Home & Kitchen',
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    currentStock: 22,
    reservedStock: 4,
    availableStock: 18,
    safetyStock: 15,
    reorderPoint: 45,
    unitCost: 89.0,
    dailyDemand: 5,
    daysOfStock: 3.6,
    status: 'REORDER_SOON',
    supplier: {
      id: 'sup-pureair',
      name: 'PureAero Filtration Systems',
      leadTimeDays: 6,
      reliabilityRate: 0.93,
      contactEmail: 'sales@pureaerofilters.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 52, dailyDemand: 6, reorderPoint: 45 },
      { date: 'Sep 13', stockLevel: 46, dailyDemand: 6, reorderPoint: 45 },
      { date: 'Sep 14', stockLevel: 40, dailyDemand: 6, reorderPoint: 45 },
      { date: 'Sep 15', stockLevel: 34, dailyDemand: 6, reorderPoint: 45 },
      { date: 'Sep 16', stockLevel: 28, dailyDemand: 5, reorderPoint: 45 },
      { date: 'Sep 17', stockLevel: 23, dailyDemand: 5, reorderPoint: 45 },
      { date: 'Sep 18', stockLevel: 18, dailyDemand: 5, reorderPoint: 45 },
    ],
    lastUpdated: '2026-09-19T09:20:00Z',
  },
  {
    id: 'inv-010',
    productId: 'prod-010',
    sku: 'SKU-DRILL-18V',
    name: 'Compact Brushless Cordless Drill Kit 18V',
    category: 'Industrial & Tools',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    currentStock: 120,
    reservedStock: 10,
    availableStock: 110,
    safetyStock: 20,
    reorderPoint: 50,
    unitCost: 74.0,
    dailyDemand: 4,
    daysOfStock: 27.5,
    status: 'HEALTHY',
    supplier: {
      id: 'sup-powertools',
      name: 'Vortex Power Instruments',
      leadTimeDays: 7,
      reliabilityRate: 0.98,
      contactEmail: 'contact@vortextools.com',
    },
    history: [
      { date: 'Sep 12', stockLevel: 135, dailyDemand: 4, reorderPoint: 50 },
      { date: 'Sep 13', stockLevel: 130, dailyDemand: 5, reorderPoint: 50 },
      { date: 'Sep 14', stockLevel: 126, dailyDemand: 4, reorderPoint: 50 },
      { date: 'Sep 15', stockLevel: 122, dailyDemand: 4, reorderPoint: 50 },
      { date: 'Sep 16', stockLevel: 118, dailyDemand: 4, reorderPoint: 50 },
      { date: 'Sep 17', stockLevel: 114, dailyDemand: 4, reorderPoint: 50 },
      { date: 'Sep 18', stockLevel: 110, dailyDemand: 4, reorderPoint: 50 },
    ],
    lastUpdated: '2026-09-19T07:15:00Z',
  },
];

export const INITIAL_MOCK_REORDERS: ReorderRecommendation[] = [
  {
    id: 'reord-001',
    productId: 'prod-001',
    sku: 'SKU-ERG-902',
    productName: 'Pro-Ergo Wireless Mechanical Keyboard',
    category: 'Electronics',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    availableStock: 10,
    dailyDemand: 11,
    leadTimeDays: 5,
    reorderPoint: 85,
    daysRemaining: 0.9,
    recommendedQuantity: 120,
    unitCost: 65.0,
    estimatedCost: 7800.0,
    urgency: 'CRITICAL',
    supplierName: 'Keyronix Components Ltd',
    supplierId: 'sup-keychron',
    explanation: {
      currentStock: 10,
      dailyDemand: 11,
      leadTimeDays: 5,
      leadTimeDemand: 55, // 11 * 5
      safetyStock: 30,
      reorderPoint: 85, // 55 + 30
      recommendedQuantity: 120,
      stockCoverageDays: 0.9,
      reason:
        'Current stock (10 units) covers approximately 0.9 days of sales, while the supplier requires 5 days to deliver. Available stock is 75 units below the reorder point of 85. Immediate replenishment of 120 units is required to prevent a complete stockout.',
    },
  },
  {
    id: 'reord-002',
    productId: 'prod-002',
    sku: 'SKU-ANC-404',
    productName: 'Noise-Cancelling Studio Headphones Gen-3',
    category: 'Electronics',
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    availableStock: 12,
    dailyDemand: 7,
    leadTimeDays: 6,
    reorderPoint: 67,
    daysRemaining: 1.7,
    recommendedQuantity: 80,
    unitCost: 110.0,
    estimatedCost: 8800.0,
    urgency: 'CRITICAL',
    supplierName: 'SonicWave Acoustics',
    supplierId: 'sup-audiotech',
    explanation: {
      currentStock: 12,
      dailyDemand: 7,
      leadTimeDays: 6,
      leadTimeDemand: 42, // 7 * 6
      safetyStock: 25,
      reorderPoint: 67, // 42 + 25
      recommendedQuantity: 80,
      stockCoverageDays: 1.7,
      reason:
        'With 12 units remaining and a 6-day supplier lead time, runout will occur in ~1.7 days. The lead time demand alone (42 units) exceeds current inventory. Order 80 units immediately.',
    },
  },
  {
    id: 'reord-003',
    productId: 'prod-007',
    sku: 'SKU-SERUM-VITC',
    productName: 'Antioxidant Vitamin C Glow Serum 30ml',
    category: 'Health & Beauty',
    locationId: 'LOC-HYD-01',
    locationName: 'Hyderabad Regional Depot',
    availableStock: 8,
    dailyDemand: 8,
    leadTimeDays: 6,
    reorderPoint: 73,
    daysRemaining: 1.0,
    recommendedQuantity: 100,
    unitCost: 18.0,
    estimatedCost: 1800.0,
    urgency: 'CRITICAL',
    supplierName: 'BioDerma Labs',
    supplierId: 'sup-derma',
    explanation: {
      currentStock: 8,
      dailyDemand: 8,
      leadTimeDays: 6,
      leadTimeDemand: 48,
      safetyStock: 25,
      reorderPoint: 73,
      recommendedQuantity: 100,
      stockCoverageDays: 1.0,
      reason:
        'Current inventory will be depleted within 24 hours. The supplier requires 6 days. Placing a 100-unit replenishment batch is critical to recover buffer stock.',
    },
  },
  {
    id: 'reord-004',
    productId: 'prod-003',
    sku: 'SKU-THERM-101',
    productName: 'Vacuum Insulated Stainless Tumbler 750ml',
    category: 'Home & Kitchen',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    availableStock: 40,
    dailyDemand: 9,
    leadTimeDays: 4,
    reorderPoint: 56,
    daysRemaining: 4.4,
    recommendedQuantity: 90,
    unitCost: 14.5,
    estimatedCost: 1305.0,
    urgency: 'REORDER_SOON',
    supplierName: 'HydroSteel Manufacturing',
    supplierId: 'sup-hydrosteel',
    explanation: {
      currentStock: 40,
      dailyDemand: 9,
      leadTimeDays: 4,
      leadTimeDemand: 36,
      safetyStock: 20,
      reorderPoint: 56,
      recommendedQuantity: 90,
      stockCoverageDays: 4.4,
      reason:
        'Stock has breached the reorder threshold (40 available vs 56 ROP). At 9 units/day, stock reaches safety buffer in 2.2 days and zero in 4.4 days. A standard 90-unit order is recommended.',
    },
  },
  {
    id: 'reord-005',
    productId: 'prod-009',
    sku: 'SKU-AIR-PURIFY',
    productName: 'True HEPA Smart Room Air Purifier H13',
    category: 'Home & Kitchen',
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    availableStock: 18,
    dailyDemand: 5,
    leadTimeDays: 6,
    reorderPoint: 45,
    daysRemaining: 3.6,
    recommendedQuantity: 40,
    unitCost: 89.0,
    estimatedCost: 3560.0,
    urgency: 'REORDER_SOON',
    supplierName: 'PureAero Filtration Systems',
    supplierId: 'sup-pureair',
    explanation: {
      currentStock: 18,
      dailyDemand: 5,
      leadTimeDays: 6,
      leadTimeDemand: 30,
      safetyStock: 15,
      reorderPoint: 45,
      recommendedQuantity: 40,
      stockCoverageDays: 3.6,
      reason:
        'Current inventory (18 units) is below the 45-unit reorder point. Given 6-day lead time and 5 units/day demand, reorder 40 units now to avoid stocking out before arrival.',
    },
  },
  {
    id: 'reord-006',
    productId: 'prod-004',
    sku: 'SKU-USB-C-240',
    productName: 'Braided 240W Thunderbolt 4 Fast Cable (2m)',
    category: 'Electronics',
    locationId: 'LOC-BLR-01',
    locationName: 'Bengaluru Tech Park Warehouse',
    availableStock: 80,
    dailyDemand: 14,
    leadTimeDays: 5,
    reorderPoint: 110,
    daysRemaining: 5.7,
    recommendedQuantity: 150,
    unitCost: 8.2,
    estimatedCost: 1230.0,
    urgency: 'REORDER_SOON',
    supplierName: 'NexLink Connectors',
    supplierId: 'sup-cabletech',
    explanation: {
      currentStock: 80,
      dailyDemand: 14,
      leadTimeDays: 5,
      leadTimeDemand: 70,
      safetyStock: 40,
      reorderPoint: 110,
      recommendedQuantity: 150,
      stockCoverageDays: 5.7,
      reason:
        'Stock of 80 units is under the 110 unit reorder line. With 14 units/day demand, current inventory covers 5.7 days, roughly matching the 5-day lead time. Reorder now to maintain safety buffer.',
    },
  },
];

export const INITIAL_MOCK_EVENTS: InventoryEvent[] = [
  {
    id: 'evt-101',
    sku: 'SKU-ERG-902',
    productName: 'Pro-Ergo Wireless Mechanical Keyboard',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    eventType: 'SALE',
    quantityChange: -4,
    previousStock: 18,
    newStock: 14,
    timestamp: '2026-09-19T09:40:00Z',
    source: 'Shopify POS Direct',
    referenceId: 'ORD-98412',
  },
  {
    id: 'evt-102',
    sku: 'SKU-ANC-404',
    productName: 'Noise-Cancelling Studio Headphones Gen-3',
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    eventType: 'SALE',
    quantityChange: -3,
    previousStock: 21,
    newStock: 18,
    timestamp: '2026-09-19T08:15:00Z',
    source: 'Amazon Multi-Channel',
    referenceId: 'ORD-98405',
  },
  {
    id: 'evt-103',
    sku: 'SKU-LUM-DESK',
    productName: 'Ultra-Slim LED Monitor Light Bar with Auto-Dimming',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    eventType: 'RESTOCK',
    quantityChange: 50,
    previousStock: 190,
    newStock: 240,
    timestamp: '2026-09-19T07:30:00Z',
    source: 'Inbound Dock Scanner',
    referenceId: 'PO-88210',
  },
  {
    id: 'evt-104',
    sku: 'SKU-SERUM-VITC',
    productName: 'Antioxidant Vitamin C Glow Serum 30ml',
    locationId: 'LOC-HYD-01',
    locationName: 'Hyderabad Regional Depot',
    eventType: 'SALE',
    quantityChange: -5,
    previousStock: 21,
    newStock: 16,
    timestamp: '2026-09-19T06:55:00Z',
    source: 'D2C Webstore',
    referenceId: 'ORD-98399',
  },
  {
    id: 'evt-105',
    sku: 'SKU-THERM-101',
    productName: 'Vacuum Insulated Stainless Tumbler 750ml',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    eventType: 'RETURN',
    quantityChange: 2,
    previousStock: 50,
    newStock: 52,
    timestamp: '2026-09-19T05:20:00Z',
    source: 'Customer Returns Processing',
    referenceId: 'RMA-3419',
  },
  {
    id: 'evt-106',
    sku: 'SKU-USB-C-240',
    productName: 'Braided 240W Thunderbolt 4 Fast Cable (2m)',
    locationId: 'LOC-BLR-01',
    locationName: 'Bengaluru Tech Park Warehouse',
    eventType: 'TRANSFER_IN',
    quantityChange: 25,
    previousStock: 70,
    newStock: 95,
    timestamp: '2026-09-18T22:10:00Z',
    source: 'Inter-Hub Line-Haul',
    referenceId: 'TRF-5501',
  },
  {
    id: 'evt-107',
    sku: 'SKU-DESK-MAT-XL',
    productName: 'Water-Resistant Felt & Vegan Leather Desk Pad XL',
    locationId: 'LOC-DEL-02',
    locationName: 'Delhi NCR Logistics Hub',
    eventType: 'ADJUSTMENT',
    quantityChange: -20,
    previousStock: 800,
    newStock: 780,
    timestamp: '2026-09-18T19:45:00Z',
    source: 'Quarterly Cycle Count Audit',
    referenceId: 'AUD-0091',
  },
  {
    id: 'evt-108',
    sku: 'SKU-DRILL-18V',
    productName: 'Compact Brushless Cordless Drill Kit 18V',
    locationId: 'LOC-BOM-01',
    locationName: 'Mumbai Central Fulfillment',
    eventType: 'SALE',
    quantityChange: -2,
    previousStock: 122,
    newStock: 120,
    timestamp: '2026-09-18T18:30:00Z',
    source: 'Wholesale B2B Portal',
    referenceId: 'ORD-98350',
  },
  {
    id: 'evt-109',
    sku: 'SKU-COFFEE-ETH',
    productName: 'Single-Origin Ethiopian Yirgacheffe Beans 1kg',
    locationId: 'LOC-BLR-01',
    locationName: 'Bengaluru Tech Park Warehouse',
    eventType: 'TRANSFER_OUT',
    quantityChange: -15,
    previousStock: 155,
    newStock: 140,
    timestamp: '2026-09-18T16:00:00Z',
    source: 'Store Replenishment Transfer',
    referenceId: 'TRF-5498',
  },
];
